### ISSUE TITLE
[Feat] 기본 도메인 API Signiture

### ISSUE THREAD

**Issue by loveysuby** [Team-Notitime/NOFFICE-SERVER#15]
## 🚀 Highlights

> 이슈 해결을 위한 목표와 방향을 작성해주세요.
- 테스트 버전 프로덕션 API 연결을 위한 API Signiture를 작성합니다.

## 📌 Tasks

- 그룹 가입 및 권한 관리
- 멤버의 그룹 내 공지 조회
- #2 
- #3 

## 📝 Details

> 상세 체크 리스트를 작성해주세요.

- [ ] 최소 API 의 req/res DTO 형식을 명시한다.
- [ ] Swagger 상에서 테스트 가능한 형태로 구성
- [ ] DTO의 `Nullable` 필드를 명시한다.
- [ ] 예외 형식에 대한 `specification`을 명시한다.
