### ISSUE TITLE
[Infrastructure] 배포 환경 Terraform IaC 프로비저닝

### ISSUE THREAD

**Issue by loveysuby** [Team-Notitime/NOFFICE-SERVER#170]
## 🚀 Highlights

> 이슈 해결을 위한 목표와 방향을 작성해주세요.
- 인프라 상태 보전 및 재구성 용이성을 위한 Terraform IaC 프로비저닝을 수행합니다.

## 📌 Tasks

> 개발을 계획 중인 기능을 나열해주세요.
- Infrastructure 모듈 구성 및 배포 인프라 이전

## 📝 Details

> 상세 체크 리스트를 작성해주세요.

- [ ] AWS Credential 대상 리스트업
- [ ] 배포 환경 module 구성
- [ ] IaC 프로비저닝 구성 및 도메인 설정 재구성
- [ ] 점검시간 및 가용 비용 예측치 파악

## 📚 Remarks

> 공유할 내용 혹은 레퍼런스를 넣어주세요.

- 세부 수행사항은 조직 내 관리문서로 기술하였습니다.
