### ISSUE TITLE
[Feat] 그룹 대표 이미지 S3 업로드 및 조회 기능

### ISSUE THREAD

**Issue by loveysuby** [Team-Notitime/NOFFICE-SERVER#18]
## 🚀 Highlights

- 그룹의 프로필 이미지 업로드 및 조회, 수정을 위한 기능을 구현합니다.

## 📌 Tasks

- 정적 이미지 파일 관리 및 탈취 방지를 위해 AWS `S3`를 사용합니다. 

## 📝 Details

- 그룹 대표 이미지는 아래 조건이 부여됩니다.
  - [x] 이미지 파일을 업로드할 수 있다.
  - [x] 이미지 파일은 변경될 수 있다.
  - [x] 이미지 파일은 원본 형태로 조회될 수 있다.
  - [ ] 이미지 파일은 축소된 형태로 조회될 수 있다.

## 📚 Remarks

> 공유할 내용 혹은 레퍼런스를 넣어주세요.
-
