### ISSUE TITLE
[CI] CI/CD pipeline 구성 

### ISSUE THREAD

**Issue by loveysuby** [Team-Notitime/NOFFICE-SERVER#4]
## 🚀 Highlights

- CI/CD 파이프라인을 구축하여 API 개발분을 테스트 가능한 배포 환경으로 자동화합니다.

## 📌 Tasks

- 모노리스 구조로 개발하는 환경이므로, AWS EB와 연결합니다.
  - API 문서화 환경을 구성하고, 접속 여부를 확인합니다.

## 📝 Details

- [ ] 개발 서버 테스트를 위한 격리된 환경을 접속 가능하도록 설정합니다.
- [ ] 프로덕션 배포 시 고려사항은 추후에 설정합니다.
- [ ] 문서화 환경 구성시 CORS 발생할 수 있으므로, 이에 대응해야 합니다.
