### ISSUE TITLE
[Docs] Swagger API 문서 구성

### ISSUE THREAD

**Issue by loveysuby** [Team-Notitime/NOFFICE-SERVER#6]
## 🚀 Highlights
- API 테스트를 위한 문서 환경을 구성합니다.

## 📌 Tasks

- Swagger 기반의 API 문서화를 제공합니다.

## 📝 Details

- [ ] 접근 제한 혹은 https 도메인 서빙에 의한 CORS를 고려합니다.
- [ ] #5 에 의한 DTO Nullable spec를 명시합니다.
- [x] 배포 도메인 서빙은 추가 이슈로 발행하므로 고려하지 않습니다.
